# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7be3ksMCYe9B3VY_CC_nWUyAX9QcuM5
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="lxyuan/distilbert-base-multilingual-cased-sentiments-student")

# Load model directly
from transformers import pipeline, AutoTokenizer, TFAutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("lxyuan/distilbert-base-multilingual-cased-sentiments-student")
model = TFAutoModelForSequenceClassification.from_pretrained("lxyuan/distilbert-base-multilingual-cased-sentiments-student")

import streamlit as st

# Streamlit UI
st.title("Text Classification")

# Text input box
text_input = st.text_area("Enter Text:", "")

import tensorflow as tf

# Submission button
if st.button("Submit"):
    # Text classification using pipeline
    result_pipe = pipe(text_input)

    # Text classification using model directly
    inputs = tokenizer(text_input, return_tensors="tf")
    inputs = {key: tf.convert_to_tensor(value) for key, value in inputs.items()}  # Convert inputs to TensorFlow tensors
    outputs = model(inputs)
    logits = outputs.logits
    predicted_class = tf.argmax(logits, axis=1).numpy()[0]

    # Display results
    st.subheader("Classification using Pipeline")
    st.write(f"Label: {result_pipe[0]['label']}, Confidence: {result_pipe[0]['score']}")

    st.subheader("Classification using Model directly")
    st.write(f"Predicted Class: {predicted_class}")
else:
  st.warning("please enter something before submitting")